package moller.javapeg.program.enumerations;

public enum FieldName {
	FNUMBER,
	DATE_TIME_ORIGINAL,
	ISO_SPEED_RATINGS,
	PIXEL_X_DIMENSION,
	PIXEL_Y_DIMENSION,
	EXPOSURE_TIME_VALUE,
	JPEG_INTERCHANGE_FORMAT,
	JPEG_INTERCHANGE_FORMAT_LENGTH;
}
