package moller.javapeg.program.enumerations;

public enum FieldName {
	APERTURE_VALUE,
	DATE_TIME_ORIGINAL,
	ISO_SPEED_RATINGS,
	PIXEL_X_DIMENSION,
	PIXEL_Y_DIMENSION,
	SHUTTER_SPEED_VALUE,
	JPEG_INTERCHANGE_FORMAT,
	JPEG_INTERCHANGE_FORMAT_LENGTH;
}
